#!/usr/bin/env python3
"""Fail-closed SIM2XR formal-gap closure verifier.

Derives obligations from repository evidence, binds hashes and witness values
into a generated Lean theorem, and refuses promotion on inconsistency.
It never invents measurements or universalizes local timing evidence.
"""
from __future__ import annotations
import hashlib, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
WITNESS = ROOT / "verified/sim2xr/2026-09-08/bidirectional_witness.json"
CLAIM = ROOT / "verified/sim2xr/2026-09-08/CLAIM.md"
REGISTRY = ROOT / "claims/REGISTRY.json"
FORMAL = ROOT / "lean4/PCSS_SIM2XR_20260908.lean"
OUT = ROOT / "lean4/PCSS_SIM2XR_FORMAL_BINDING_GENERATED.lean"

def sha256(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()

def fail(msg: str) -> None:
    print("FORMAL_GAP_CLOSURE: FAIL:", msg)
    raise SystemExit(2)

w = json.loads(WITNESS.read_text())
registry = json.loads(REGISTRY.read_text())
claim = CLAIM.read_text()
formal = FORMAL.read_text()

for t in ("one_step", "finite_descent", "reconstruction",
          "invariant_preserved", "identity_stack", "bound_to_run_id"):
    if f"theorem {t}" not in formal:
        fail(f"missing formal theorem: {t}")
if "sorry" in formal.lower():
    fail("formal source contains sorry")

cases = w.get("cases", [])
if len(cases) != 5:
    fail(f"expected 5 witnesses, got {len(cases)}")
if not w.get("all_bidirectional_witnesses_pass"):
    fail("witness packet does not assert all bidirectional witnesses pass")
for i, c in enumerate(cases):
    if not c.get("forward_reverse_pass"):
        fail(f"case {i} lacks forward/reverse pass")
    for k in ("intertwining_residual", "task_error", "reconstruction_error"):
        if c.get(k) != 0.0:
            fail(f"case {i} has nonzero {k}")

ratios = [float(c["speedup"]) for c in cases]
median = sorted(ratios)[len(ratios)//2]
maximum = max(ratios)
if abs(median - float(w["median_speedup"])) > 1e-12:
    fail("median_speedup disagrees with raw witness cases")
if abs(maximum - float(w["max_speedup"])) > 1e-12:
    fail("max_speedup disagrees with raw witness cases")

entry = next((x for x in registry["claims"]
              if x.get("id") == "sim2xr-invariant-sector-20260908"), None)
if entry is None:
    fail("SIM2XR registry entry missing")
reported = entry.get("result", {}).get("reported_speedups")
if reported is not None and [round(float(x), 2) for x in reported] != [round(x, 2) for x in ratios]:
    fail("registry speedup vector disagrees with witness packet")
cert_max = entry.get("result", {}).get("certificate_max")
if cert_max is not None and abs(float(cert_max) - maximum) > 1e-9:
    fail(f"stale registry certificate_max {cert_max} != witness max {maximum}")

if "not an asymptotic theorem" not in claim or "not a universal" not in claim:
    fail("claim boundary language weakened")
if "Lean workflow binding pending" in claim:
    fail("claim still declares Lean binding pending")

scale = 1_000_000
scaled = [round(x * scale) for x in ratios]
src_hash, wit_hash, claim_hash = map(sha256, (FORMAL, WITNESS, CLAIM))
run_id = "sim2xr-invariant-sector-20260908"
generated = f'''/- GENERATED BY governor/close_sim2xr_formal_gap.py -/
namespace PCSS.SIM2XR.FormalBinding

def runId : String := "{run_id}"
def sourceHash : String := "{src_hash}"
def witnessHash : String := "{wit_hash}"
def claimHash : String := "{claim_hash}"
def scale : Nat := {scale}
def witnessRatios : List Nat := [{",".join(map(str, scaled))}]

theorem run_id_bound : runId = "{run_id}" := rfl
theorem source_hash_bound : sourceHash = "{src_hash}" := rfl
theorem witness_hash_bound : witnessHash = "{wit_hash}" := rfl
theorem claim_hash_bound : claimHash = "{claim_hash}" := rfl
theorem five_witnesses_gt_one : ∀ x ∈ witnessRatios, x > scale := by
  intro x hx
  simp [witnessRatios] at hx
  rcases hx with rfl | rfl | rfl | rfl | rfl <;> decide

structure Gates where
  I R Q Qinv Omega X L : Bool

def closed : Gates := {{ I:=true, R:=true, Q:=true, Qinv:=true, Omega:=true, X:=true, L:=true }}

def admissible (g : Gates) : Prop :=
  g.I = true ∧ g.R = true ∧ g.Q = true ∧ g.Qinv = true ∧
  g.Omega = true ∧ g.X = true ∧ g.L = true

theorem closed_admissible : admissible closed := by
  constructor; rfl
  constructor; rfl
  constructor; rfl
  constructor; rfl
  constructor; rfl
  constructor; rfl
  rfl

end PCSS.SIM2XR.FormalBinding
'''
OUT.write_text(generated)
print("FORMAL_GAP_CLOSURE: generated", OUT)
print("FORMAL_GAP_CLOSURE: source_sha256", src_hash)
print("FORMAL_GAP_CLOSURE: witness_sha256", wit_hash)
print("FORMAL_GAP_CLOSURE: claim_sha256", claim_hash)
print("FORMAL_GAP_CLOSURE: median", w["median_speedup"])
print("FORMAL_GAP_CLOSURE: maximum", w["max_speedup"])
print("FORMAL_GAP_CLOSURE: PASS_PRELEAN")
