/-!
# Bidirectional Gap Closure — proof-governed problem derivation

This module coalesces the verified Speedup theorem substrate into one operational
closure object. It deliberately proves only consequences of already-proven
premises; it does not claim that a concrete external embedding, runtime
measurement, or client integration is proven merely by being named here.

Lean 4 core only; no Mathlib; no `sorry`; no `axiom`.

Operational chain:
  forward descent -> finite trajectory correspondence -> observable correctness
  reverse section -> reconstruction -> surjectivity
  work model -> exact arithmetic-work boundary
  evidence certificate -> fail-closed publication condition

External clients (OmniRoute/OpenCode/Kilo) may treat the closure certificate as
an input/output protocol boundary; live connectivity remains an external fact.
-/

import SpeedupLean

namespace BidirectionalGapClosure

open AGDGemmProjection
open AGDGemmReconstruction
open AGDGemmSpeedup
open AGDGemmWork
open PCSS

universe u v w

/-- The mathematical closure package required before a reduced problem may be
considered semantically closed in both directions. -/
structure SemanticClosure
    {State : Type u} {Reduced : Type v} {Obs : Type w}
    (T : State → State) (Tbar : Reduced → Reduced)
    (π : State → Reduced) (σ : Reduced → State)
    (observe : State → Obs) (observeReduced : Reduced → Obs) where
  intertwines : Intertwines T Tbar π
  observable : ObservablePreserved π observe observeReduced
  section : Section π σ

/-- Forward closure generated by a single intertwining witness. -/
theorem forward_gap_closure
    {State : Type u} {Reduced : Type v} {Obs : Type w}
    (T : State → State) (Tbar : Reduced → Reduced)
    (π : State → Reduced)
    (observe : State → Obs) (observeReduced : Reduced → Obs)
    (hI : Intertwines T Tbar π)
    (hO : ObservablePreserved π observe observeReduced) :
    WellDefined π T ∧
    (∀ n x, π (iterate T n x) = iterate Tbar n (π x)) ∧
    (∀ n x, observe (iterate T n x) =
      observeReduced (iterate Tbar n (π x))) := by
  exact projection_closure T Tbar π observe observeReduced hI hO |>.elim
    (fun h => h)

/-- Reverse closure generated by a section and the same forward witness. -/
theorem reverse_gap_closure
    {State : Type u} {Reduced : Type v} {Obs : Type w}
    (T : State → State) (Tbar : Reduced → Reduced)
    (π : State → Reduced) (σ : Reduced → State)
    (hS : Section π σ)
    (hI : Intertwines T Tbar π) :
    (π ∘ σ = id) ∧
    Function.Injective σ ∧
    Function.Surjective π ∧
    (π ∘ T ∘ σ = Tbar) ∧
    (∀ n q, π (iterate T n (σ q)) = iterate Tbar n q) := by
  exact reconstruction_closure π σ T Tbar hS hI

/-- Full semantic bidirectional closure. -/
theorem bidirectional_semantic_closure
    {State : Type u} {Reduced : Type v} {Obs : Type w}
    (T : State → State) (Tbar : Reduced → Reduced)
    (π : State → Reduced) (σ : Reduced → State)
    (observe : State → Obs) (observeReduced : Reduced → Obs)
    (H : SemanticClosure T Tbar π σ observe observeReduced) :
    (∀ n x, π (iterate T n x) = iterate Tbar n (π x)) ∧
    (∀ n x, observe (iterate T n x) =
      observeReduced (iterate Tbar n (π x))) ∧
    (π ∘ σ = id) ∧
    Function.Injective σ ∧
    Function.Surjective π ∧
    (π ∘ T ∘ σ = Tbar) := by
  have hf := forward_gap_closure T Tbar π observe observeReduced
    H.intertwines H.observable
  have hr := reverse_gap_closure T Tbar π σ H.section H.intertwines
  exact ⟨hf.2.1, hf.2.2, hr.1, hr.2.1, hr.2.2.1, hr.2.2.2.1⟩

/-- Semantic closure plus the canonical GEMM work theorem. -/
theorem bidirectional_work_closure
    {State : Type u} {Reduced : Type v} {Obs : Type w}
    (T : State → State) (Tbar : Reduced → Reduced)
    (π : State → Reduced) (σ : Reduced → State)
    (observe : State → Obs) (observeReduced : Reduced → Obs)
    (H : SemanticClosure T Tbar π σ observe observeReduced) :
    (∀ n x, π (iterate T n x) = iterate Tbar n (π x)) ∧
    (∀ n x, observe (iterate T n x) =
      observeReduced (iterate Tbar n (π x))) ∧
    (π ∘ σ = id) ∧
    Function.Surjective π ∧
    WorkModelHolds := by
  have hs := bidirectional_semantic_closure T Tbar π σ observe observeReduced H
  exact ⟨hs.1, hs.2.1, hs.2.2.1, hs.2.2.2.2.1, work_model_closure⟩

/-- A concrete evidence certificate can be promoted to a formally admissible
closure result exactly when its declared Lean/formal gate and other gates pass.
This theorem intentionally does not fabricate those gates. -/
theorem evidence_gate_closure
    (c : EvidenceCertificate)
    (h : publishable c) :
    c.integrity = true ∧
    c.reproducibility = true ∧
    c.quotientForward = true ∧
    c.reconstructionReverse = true ∧
    c.invariants = true ∧
    c.performance = true ∧
    c.lean = true :=
  publish_requires_all_gates c h

/-- The seven PCSS gates therefore form a necessary condition for a verified
claim in the operational derivation pipeline. -/
theorem verified_claim_requires_full_gate
    (c : EvidenceCertificate)
    (h : verifiedResult c) :
    publishable c :=
  h

/-- If the runtime gate is not satisfied, this kernel makes no runtime
speedup claim from the exact work-ratio theorem. -/
theorem runtime_boundary_preserved :
    measuredHundredths = 1596 ∧
    workRatio (fullWork 1024 1024 1024) (quotientWork 256 256 1024) = 16 ∧
    measuredHundredths ≠
      workRatio (fullWork 1024 1024 1024) (quotientWork 256 256 1024) * 100 := by
  exact ⟨rfl, canonical_workRatio,
    measured_hundredths_neq_work_ratio_times_100⟩

/-- A client-facing boundary classification. This is deliberately structural:
closed means the caller supplied a complete mathematical closure witness;
boundary means the caller supplied an explicit explanation of what is missing.
No theorem here turns an arbitrary proposition into a proof automatically. -/
inductive DerivationResult
    {State : Type u} {Reduced : Type v} {Obs : Type w}
    where
  | closed (closure : SemanticClosure T Tbar π σ observe observeReduced)
  | boundary (reason : String)

/-- When the full closure premises are available, the derivation result is the
closed branch. This is the operational entry point for proof-producing clients.
-/
def closeProblem
    {State : Type u} {Reduced : Type v} {Obs : Type w}
    (T : State → State) (Tbar : Reduced → Reduced)
    (π : State → Reduced) (σ : Reduced → State)
    (observe : State → Obs) (observeReduced : Reduced → Obs)
    (h : SemanticClosure T Tbar π σ observe observeReduced) :
    DerivationResult :=
  .closed h

theorem closeProblem_is_closed
    {State : Type u} {Reduced : Type v} {Obs : Type w}
    (T : State → State) (Tbar : Reduced → Reduced)
    (π : State → Reduced) (σ : Reduced → State)
    (observe : State → Obs) (observeReduced : Reduced → Obs)
    (h : SemanticClosure T Tbar π σ observe observeReduced) :
    ∃ closure, closeProblem T Tbar π σ observe observeReduced h =
      .closed closure :=
  ⟨h, rfl⟩

end BidirectionalGapClosure
