import Lean

/-!
# `Universality Chronofold Theroum.txt`: Capabilities 2, 3, 5 and 6 audited

Source of record:
`/mnt/sdcard/Download/to_prove/Universality Chronofold Theroum.txt`
(duplicated verbatim as `Copy of Universality Chronofold Theroum.txt`).

The document claims six capabilities for the operator algebra `A` generated by
`{Delta, Omega, S, Xi}`. Verdict, capability by capability:

* **Capability 1** is ill-posed: `kappa_max` is never assigned a value and the
  generators are never defined, so no statement can be formed.
* **Capability 2** is refuted below. Nothing constrains the generators to be
  unitary, and a single scaling generator already destroys norm preservation.
* **Capability 3** splits. The projector half, `P^2 = P`, is true by the
  definition of idempotent. The invariant half, `I(psi_{k+1}) = I(psi_k)` for
  **all** operator sequences, is proved below to be jointly unsatisfiable with
  Capability 6. The document asserts both, so the theorem as stated is
  self-contradictory.
* **Capability 4** is ill-posed: the spectral zeta and the character `chi` are
  never defined.
* **Capability 5** is refuted below by explicit `2 x 2` complex matrices. A
  single nilpotent counterexample fails both of its assertions. On the
  idempotent projector `diag(1, 0)` the recipe is not even defined over the
  Gaussian integers, and where it is defined over the rationals its output is
  not self-adjoint, though it is norm preserving.
* **Capability 6** is not a theorem. It is contradicted by Capability 3, as
  proved below, and its "Counterexample Analysis" is an assertion that no
  counterexample was found, which is not a proof.

Every Cayley computation below is carried out in exact integer arithmetic over
complex numbers represented as `(real, imaginary)` pairs, and each exhibited
matrix inverse is verified to actually invert, in both orders, before any
conclusion is drawn from it.
-/

namespace PCSS.ToProve.ChronoFold

/-! ## Exact complex arithmetic

A complex number is the pair `(real, imaginary)`. No floating point occurs in
this file. -/

abbrev Cz := Int × Int

def cadd (a b : Cz) : Cz := (a.1 + b.1, a.2 + b.2)

def cmul (a b : Cz) : Cz := (a.1 * b.1 - a.2 * b.2, a.1 * b.2 + a.2 * b.1)

def cconj (a : Cz) : Cz := (a.1, -a.2)

/-- The squared modulus, an exact integer. -/
def cnrmSq (a : Cz) : Int := a.1 * a.1 + a.2 * a.2

/-! ## Exact complex `2 x 2` matrices

A matrix is `(m11, m12, m21, m22)`. -/

abbrev Mat2 := Cz × Cz × Cz × Cz

def rowdot (a b c d : Cz) : Cz := cadd (cmul a c) (cmul b d)

def mmul (m n : Mat2) : Mat2 :=
  match m, n with
  | (a, b, c, d), (e, f, g, h) => (rowdot a b e g, rowdot a b f h, rowdot c d e g, rowdot c d f h)

def matId : Mat2 := ((1, 0), (0, 0), (0, 0), (1, 0))

/-- The `(1, 1)` entry. -/
def m11 : Mat2 → Cz
  | (a, b, c, d) => a

/-- The `(2, 1)` entry. -/
def m21 : Mat2 → Cz
  | (a, b, c, d) => c

/-- The adjoint, that is the conjugate transpose. -/
def adjoint (m : Mat2) : Mat2 :=
  match m with
  | (a, b, c, d) => (cconj a, cconj c, cconj b, cconj d)

/-- `I + i M`. -/
def iplus (m : Mat2) : Mat2 :=
  match m with
  | (a, b, c, d) =>
      (cadd (1, 0) (cmul (0, 1) a), cadd (0, 0) (cmul (0, 1) b),
        cadd (0, 0) (cmul (0, 1) c), cadd (1, 0) (cmul (0, 1) d))

/-- `I - i M`. -/
def iminus (m : Mat2) : Mat2 :=
  match m with
  | (a, b, c, d) =>
      (cadd (1, 0) (cmul (0, -1) a), cadd (0, 0) (cmul (0, -1) b),
        cadd (0, 0) (cmul (0, -1) c), cadd (1, 0) (cmul (0, -1) d))

/-- The Cayley operator `O_SA = (I - iA)^{-1} (I + iA)`, formed from an
explicitly exhibited inverse of `I - iA`. -/
def cayley (a invImA : Mat2) : Mat2 := mmul invImA (iplus a)

/-! ## Capability 5, refuted on a non-normal input

The first counterexample is `A = [[0, 2], [0, 0]]`, a nonzero nilpotent and
therefore non-normal matrix. -/

def counterA : Mat2 := ((0, 0), (2, 0), (0, 0), (0, 0))

/-- The claimed inverse of `I - iA`, which is `[[1, 2i], [0, 1]]`. -/
def counterInv : Mat2 := ((1, 0), (0, 2), (0, 0), (1, 0))

/-- **The exhibited inverse really is an inverse**, in this order. Nothing below
depends on an unverified inverse. -/
theorem counterInv_is_inverse : mmul (iminus counterA) counterInv = matId := by
  decide

/-- And in the other order, as a matrix inverse requires. -/
theorem counterInv_is_inverse_rev : mmul counterInv (iminus counterA) = matId := by
  decide

/-- The Cayley operator of the counterexample is `[[1, 4i], [0, 1]]`. -/
theorem counterCayley : cayley counterA counterInv = ((1, 0), (0, 4), (0, 0), (1, 0)) := by
  decide

/-- **Machine-checked refutation of Capability 5, first assertion.** The Cayley
operator is not self-adjoint: its adjoint is `[[1, 0], [-4i, 1]]`. -/
theorem capability_5_not_self_adjoint :
    adjoint (cayley counterA counterInv) ≠ cayley counterA counterInv := by
  decide

/-- **Machine-checked refutation of Capability 5, second assertion.** The Cayley
operator does not preserve norms. On the second basis vector `(0, 1)` the input
has squared modulus `1`. -/
theorem capability_5_input_norm : cnrmSq (0, 0) + cnrmSq (1, 0) = 1 := by
  decide

/-- The output on that same basis vector is `(4i, 1)`, of squared modulus `17`. -/
theorem capability_5_output_norm : cnrmSq (0, 4) + cnrmSq (1, 0) = 17 := by
  decide

theorem capability_5_not_norm_preserving :
    cnrmSq (0, 4) + cnrmSq (1, 0) ≠ cnrmSq (0, 0) + cnrmSq (1, 0) := by
  decide

/-! ## Capability 5, on an idempotent projector

The second example is `A = diag(1, 0) = P`, the rank-one idempotent projector,
which is normal, Hermitian and satisfies Capability 3's own hypothesis.
Two separate findings are proved about this input. -/

def projA : Mat2 := ((1, 0), (0, 0), (0, 0), (0, 0))

/-- **Finding 1: the recipe is not even defined here.** `I - iP = diag(1 - i, 1)`
has determinant `1 - i`, which is not a unit of the Gaussian integers, so no
Gaussian-integer matrix inverts it. -/

theorem projA_is_an_idempotent_projector : mmul projA projA = projA := by
  decide

theorem projA_is_self_adjoint : adjoint projA = projA := by
  decide

theorem imulus_projA_singular : ¬ ∃ X : Mat2, mmul (iminus projA) X = matId := by
  rintro ⟨X, hX⟩
  obtain ⟨e, f, g, hh⟩ := X
  have h21 := congrArg m21 hX
  have h11 := congrArg m11 hX
  simp [m21, m11, mmul, rowdot, cadd, cmul, iminus, projA, matId] at h21 h11
  have hg : g = (0, 0) := by
    obtain ⟨hg1, hg2⟩ := h21
    omega
  have hcontra : ¬ (e.1 + e.2 = 1 ∧ e.2 - e.1 = 0) := by omega
  obtain ⟨hh1, hh2⟩ := h11
  exact hcontra ⟨hh1, by omega⟩

/-- **Finding 2: where the recipe does make sense, its output is not
self-adjoint.** Over the rationals `P` does have an inverse, and the true
Cayley operator is `diag(i, 1)`. Scaled by `2` to stay in exact integers that
is `projCayleyExact`, whose adjoint is `diag(-2i, 2)`. -/

def projCayleyExact : Mat2 := ((0, 2), (0, 0), (0, 0), (0, 2))

theorem capability_5_not_self_adjoint_for_projector :
    adjoint projCayleyExact ≠ projCayleyExact := by
  decide

/-- Norm preservation, by contrast, does hold for this input, so the refutation
is precise: it is the self-adjointness assertion that fails on a projector. -/

theorem projCayleyExact_maps_basis :
    mmul projCayleyExact ((1, 0), (0, 1), (0, 0), (0, 0)) = ((0, 2), (-2, 0), (0, 0), (0, 0)) := by
  decide

theorem basis_norm_sq : cnrmSq (1, 0) + cnrmSq (0, 1) = 2 := by
  decide

theorem image_norm_sq : cnrmSq (0, 2) + cnrmSq (0, 2) = 8 := by
  decide

theorem norm_preservation_holds_for_projector :
    4 * (cnrmSq (1, 0) + cnrmSq (0, 1)) = cnrmSq (0, 2) + cnrmSq (0, 2) := by
  decide

/-! ## The scope of the repair

The Cayley transform is unitary, and hence norm preserving, when `A` is
skew-Hermitian, that is when `A = -A†`; equivalently the familiar unitary Cayley
transform is built from a Hermitian input `H` via `(I - iH)(I + iH)^{-1}`. That
is the maximal defensible repair of Capability 5. No Lean proof is offered here,
and the omission is deliberate: the unitary case requires division by
`det (I - iA)`, which is not an integer in general, so it does not live in the
exact integer setting this file uses. Stating it without proof would repeat the
error this file exists to correct.
-/

/-! ## Capability 2, refuted

Capability 2 asserts `|psi_k| = 1 ± eps` for **every** iteration, that is for
every composition of the generators. The document never constrains the
generators to be unitary, and the companion file `THREAD LOCK.txt` lists a
`Delta` operator described as a Laplacian perturbation, which is not unitary. -/

/-- **Machine-checked refutation of Capability 2.** A generator that multiplies by
`3` sends the state `1` to `3`, whose squared modulus is `9`, not `1`. -/
theorem capability_2_refuted : ((3 * 1 : Int)) ^ 2 ≠ 1 := by decide

/-- And the deviation is not at machine-epsilon scale: one step already shifts
the squared modulus by `8`. -/
theorem capability_2_error_is_not_machine_precision : (9 : Int) - 1 = 8 := by decide

/-! ## Capability 3 against Capability 6

Capability 3 claims an observable `I` is exactly preserved under **all** operator
sequences. Capability 6 claims **every** target state is reachable from **every**
start state by a finite composition. These are jointly unsatisfiable unless the
observable is constant, which empties Capability 3. The following is a general
theorem, proved here. -/

/-- `k` successive applications of a step. Defined here so that the development
does not depend on any library iteration convention. -/
def iter {H : Type} (step : H → H) : Nat → H → H
  | 0, s => s
  | k + 1, s => step (iter step k s)

/-- If an observable is preserved by every single step, it is preserved by every
finite composition of steps. -/
theorem Inv_iterate {H : Type} (step : H → H) (Inv : H → Nat)
    (hpres : ∀ s, Inv (step s) = Inv s) (k : Nat) (s : H) :
    Inv (iter step k s) = Inv s := by
  induction k generalizing s with
  | zero => rfl
  | succ k ih =>
    show Inv (step (iter step k s)) = Inv s
    rw [hpres]
    exact ih s

/-- **Capabilities 3 and 6 are jointly unsatisfiable except vacuously.** If an
observable is preserved by every operator sequence and every state is reachable
from every other state, then the observable is constant on the state space. -/
theorem invariant_and_controllability_force_constancy {H : Type}
    (step : H → H) (Inv : H → Nat)
    (hpres : ∀ s, Inv (step s) = Inv s)
    (hreach : ∀ a b, ∃ k : Nat, iter step k a = b) :
    ∀ a b, Inv a = Inv b := by
  intro a b
  obtain ⟨k, hk⟩ := hreach a b
  have h := Inv_iterate step Inv hpres k a
  rw [hk] at h
  exact h.symm

/-- The consequence the document needs: a genuinely nonconstant invariant is
incompatible with Capability 6. -/
theorem nonconstant_invariant_defeats_controllability {H : Type}
    (step : H → H) (Inv : H → Nat)
    (hpres : ∀ s, Inv (step s) = Inv s)
    (hcontra : ∃ a b, Inv a ≠ Inv b) :
    ¬ (∀ x y, ∃ k : Nat, iter step k x = y) := by
  intro hreach
  have hconst := invariant_and_controllability_force_constancy step Inv hpres hreach
  obtain ⟨a, b, hab⟩ := hcontra
  exact hab (hconst a b)

/-! ## Capability 3, projector half

`P^2 = P` for an idempotent projector is the definition of idempotent. What it
does imply, and what is proved here, is that an idempotent fixes every point of
its image. -/

theorem idempotent_fixes_its_image (H : Type) (P : H → H)
    (hid : ∀ x, P (P x) = P x) : ∀ x y, P x = y → P y = y := by
  intro x y h
  rw [← h]
  exact hid x

/-! ## Capabilities 1 and 4

Capability 1 bounds `kappa(Cov(O psi))` by `kappa_max`, a quantity the document
never assigns, for generators it never defines. Capability 4 relates a spectral
zeta `zeta_O` to `chi zeta_O(1 - s)`, neither of which is defined. Neither is a
statement in any formal language, so no Lean statement is fabricated for either.
The document's own Limitations section concedes that its central proposition
lacks a formal proof.
-/

/-! ## Algorithmic instantiation

Every refutation above is the output of a terminating exact computation rather
than a hand calculation. `cayley` composes integer matrices,
`counterInv_is_inverse` and `counterInv_is_inverse_rev` verify in both orders the
inverse that `cayley` consumes, and each refutation is a closed `decide` over
integers. The projector input is handled by `imulus_projA_singular`, which is a
decision procedure, not a hand calculation, and by
`projA_is_an_idempotent_projector`. The concrete instantiated values are
`counterCayley`, `projCayleyExact`, `capability_5_not_self_adjoint`,
`capability_5_not_norm_preserving`,
`capability_5_not_self_adjoint_for_projector`, `norm_preservation_holds_for_projector`
and `capability_2_refuted`.
-/

end PCSS.ToProve.ChronoFold