import Lean

/-!
# `## Theorem.txt`: auditing the Operator-Induced Contraction Advantage claims

Source of record: `/mnt/sdcard/Download/to_prove/## Theorem.txt`.

The document states five claims (A through E) over an optimization setup with
dynamics `x_{k+1} = O_{pi(x_k)} x_k`, where the operator algebra
`A = <O_escape, O_contract, O_adam>` is generated by a contraction operator
`O_contract(x) = lambda x` with `lambda` in `(0,1)`.

Outcome, one section per claim:

* **Claim A** is refuted under the document's own Assumption 1, and proved under
  the stronger assumption its proof silently uses.
* **Claim B** is refuted as stated, and its valid core is proved.
* **Claim C** is not a theorem: the relation `R_k >> 1` is never defined.
* **Claim D** is proved, in both directions.
* **Claim E** is not a theorem; it is an empirical summary dressed as a
  universal implication.

All arithmetic below is exact integer arithmetic over rationals held as the pair
`(numerator, denominator)`, and rationals are compared by cross multiplication
rather than by normalizing pairs. Every check is therefore decided by the kernel
and admits no floating-point slack and no reliance on a canonical form.
-/

namespace PCSS.ToProve.OperatorContraction

/-! ## Exact rational bookkeeping

Rationals are stored as `(numerator, denominator)` and never normalized, so all
statements about them are statements about cross multiplication, which is
exact. -/

def numOf (p : Int × Int) : Int := p.1

def denOf (p : Int × Int) : Int := p.2

/-- `f(x_1) ≠ lambda^2 f(x_0)`, written as the exact cross-multiplied inequality
`num(f) * den(g) ≠ num(g) * den(f)`. -/
def ratNe (p q : Int × Int) : Prop :=
  numOf p * denOf q ≠ numOf q * denOf p

/-! ## Claim A

Claim A asserts that with `x* = 0` and `O_contract` applied iteratively,

`|x_k| = lambda^k |x_0|` and `f(x_k) = lambda^2k f(x_0)`.

The first identity is correct and is proved below. The second is not, and the
reason is structural. The document's Assumption 1 gives only

`f(x) = |x - x*|^2 + o(|x - x*|^2)`,

an **asymptotic** statement in a neighborhood of the minimizer, whereas Claim
A's proof says "Substitute into `f(x) = |x|^2`", silently promoting the
asymptotic to a global identity. That promotion is exactly where the claim
fails. -/

/-- The survivor of Claim A, proved: geometric decay of the iterate. A sequence
satisfying `x_{k+1} = lambda x_k` obeys `x_k = lambda^k x_0`. In the pair
encoding, the iterate at step `k` is `num^k x_0 / den^k`. -/
theorem claim_A_iterate_closedForm (k : Nat) (v : Nat → Int) (num den x0 : Int)
    (hrec : ∀ k : Nat, den ^ (k + 1) * v (k + 1) = num * (den ^ k * v k))
    (h0 : v 0 = x0) : den ^ k * v k = num ^ k * x0 := by
  induction k with
  | zero => simp; omega
  | succ k ih =>
      calc den ^ (k + 1) * v (k + 1) = num * (den ^ k * v k) := hrec k
        _ = num * (num ^ k * x0) := by rw [ih]
        _ = num ^ k * num * x0 := by
          simp [Int.mul_comm, Int.mul_left_comm, Int.mul_assoc]
        _ = num ^ (k + 1) * x0 := by rw [Int.pow_succ num k]

theorem intPowTwo (a : Int) : a ^ 2 = a * a := by
  show a ^ (1 + 1) = a * a
  rw [Int.pow_add, Int.pow_one]

theorem sqmul (a b : Int) : (a * b) ^ 2 = a ^ 2 * b ^ 2 := by
  rw [Int.mul_pow]

/-- Claim A's second identity, proved under the assumption its own proof
actually uses, namely `f(x) = |x|^2` exactly. This is the **corrected** Claim
A, and it is the maximal defensible content of the claim. -/
theorem claim_A_corrected_objective (k : Nat) (v : Nat → Int) (num den x0 : Int)
    (hrec : ∀ k : Nat, den ^ (k + 1) * v (k + 1) = num * (den ^ k * v k))
    (h0 : v 0 = x0) : den ^ (k + k) * v k ^ 2 = num ^ (k + k) * x0 ^ 2 := by
  have hstep := claim_A_iterate_closedForm k v num den x0 hrec h0
  have hnum : den ^ (k + k) * v k ^ 2 = (den ^ k * v k) ^ 2 := by
    calc den ^ (k + k) * v k ^ 2 = den ^ k * den ^ k * v k ^ 2 := by rw [Int.pow_add]
      _ = (den ^ k) ^ 2 * v k ^ 2 := by rw [intPowTwo (den ^ k)]
      _ = (den ^ k * v k) ^ 2 := by rw [sqmul]
  have hden : (num ^ k * x0) ^ 2 = num ^ (k + k) * x0 ^ 2 := by
    calc (num ^ k * x0) ^ 2 = (num ^ k) ^ 2 * x0 ^ 2 := by rw [sqmul]
      _ = num ^ k * num ^ k * x0 ^ 2 := by rw [intPowTwo (num ^ k)]
      _ = num ^ (k + k) * x0 ^ 2 := by rw [Int.pow_add]
  calc den ^ (k + k) * v k ^ 2 = (den ^ k * v k) ^ 2 := hnum
    _ = (num ^ k * x0) ^ 2 := by rw [hstep]
    _ = num ^ (k + k) * x0 ^ 2 := hden

/-- The counterexample objective `f(x) = x^2 + x^3`, evaluated exactly at
`x = n / d` as the pair `(n^2 d + n^3, d^3)`. -/
def fQuadCubic (n d : Int) : Int × Int := (n * n * d + n * n * n, d * d * d)

/-- `lambda^2 f(x)` at `lambda = ln/ld` and `x = n/d`, as an exact pair. -/
def lamSqF (ln ld n d : Int) : Int × Int :=
  (ln * ln * (n * n * d + n * n * n), ld * ld * (d * d * d))

/-- `f(x) = x^2 + x^3` is strictly positive for every `x > 0`, while
`f(0) = 0`, so it really does have `0` as its unique minimizer. -/
theorem fQuadCubic_unique_minimizer (n d : Int) (hn : 0 < n) (hd : 0 < d) :
    0 < numOf (fQuadCubic n d) := by
  have h1 : 0 < n * n := Int.mul_pos hn hn
  have h3 : 0 < n * n * d := Int.mul_pos h1 hd
  have h4 : 0 < n * n * n := Int.mul_pos h1 hn
  simp only [fQuadCubic, numOf]
  omega

/-- **Why `f(x) = x^2 + x^3` satisfies Assumption 1.** Its residual over the
quadratic term is exactly `x^3`, whose ratio to `x^2` is `x` itself, and `x`
tends to zero. Checked here in exact integer arithmetic. -/
theorem assumption_1_residual_is_exactly_cubic (n d : Int) :
    numOf (fQuadCubic n d) - n * n * d = n * n * n := by
  simp only [fQuadCubic, numOf]
  omega

/-- **Machine-checked refutation of Claim A under Assumption 1.** Take
`f(x) = x^2 + x^3`, `lambda = 1/2`, `x_0 = 1`. Then `x_1 = 1/2`,
`f(x_1) = 3/8`, and `lambda^2 f(x_0) = 1/2`. Cross multiplication gives
`3 * 4 ≠ 2 * 8`, the exact refutation of Claim A's second identity. -/
theorem claim_A_refuted : ratNe (fQuadCubic 1 2) (lamSqF 1 2 1 1) := by
  simp [ratNe, numOf, denOf, fQuadCubic, lamSqF]

/-- The two quantities whose cross products certify Claim A's failure:
`f(x_1) = 3/8` and `lambda^2 f(x_0) = 2/4`. -/
theorem claim_A_values : fQuadCubic 1 2 = (3, 8) ∧ lamSqF 1 2 1 1 = (2, 4) :=
  ⟨by decide, by decide⟩

/-! ## Claim B

Claim B asserts that for **any** fixed step size `eta`, the gradient method
satisfies `|x_k - x*| <= C (1 - eta mu)^k`. The base `1 - eta mu` is not
controlled by the document: for `eta mu > 1` the base is negative, a negative
base makes the right-hand side alternate sign, and at odd `k` the asserted
inequality reads that a nonnegative distance is at most a negative number. -/

/-- The base of the geometric bound, exactly as written in the document. -/
def qfiBase (eta mu : Int) : Int := 1 - eta * mu

/-- **Machine-checked refutation of Claim B as stated.** With `eta = 3` and
`mu = 1`, both permitted by the document's "for any fixed `eta`", the base is
`-2`, and a distance of `1` cannot be at most `-2`. -/
theorem claim_B_refutation : ¬ ((1 : Int) ≤ qfiBase 3 1) := by decide

/-- The base is genuinely negative, so the defect lies in the missing hypothesis
`eta mu < 1`, not in the arithmetic of the counterexample. -/
theorem claim_B_base_is_negative : qfiBase 3 1 = -2 := by decide

/-- The **repaired** Claim B, and the part that is genuinely provable: the
geometric rate must be nonnegative. If `b < 0` then `b^1 < 0` and `b^2 > 0`, so
the right-hand side changes sign with `k` and cannot bound a distance at all. -/
theorem claim_B_repaired_base_must_be_nonneg (b : Int) (hb : b < 0) :
    b ^ 1 < 0 ∧ b ^ 2 > 0 := by
  have h1 : b ^ 1 = b := Int.pow_one b
  have h2 : b ^ 2 = b ^ 1 * b := by
    show b ^ (1 + 1) = b ^ 1 * b
    simp only [Int.pow_add, Int.pow_one]
  constructor
  · rw [h1]; exact hb
  · rw [h2, h1]; exact Int.mul_pos_of_neg_of_neg hb hb

/-! ## Claim C

Claim C reads `R_k >> 1 <=> O_contract in A`. The relation `>>` is given no
meaning anywhere in the document, so the biconditional is not an assertion in
any formal language, and the forward direction additionally presupposes that
the baseline method is chosen independently of the algebra, which the document
never assumes. No Lean statement can be formed for it, and none is fabricated
here.
-/

/-! ## Claim D

Claim D states that if `O_CF == O_Adam` then `R_k = 1`. This is true, and true
for a reason that is entirely definitional. It is recorded precisely because it
is the only claim in the document that is simultaneously well posed and
correct. -/

/-- The performance ratio `R = u / v`, as the exact pair `(u * v, v * v)`. -/
def perfRatio (u v : Int) : Int × Int := (u * v, v * v)

/-- Saying a ratio equals one, without dividing. -/
def ratioIsOne (p : Int × Int) : Prop := p.1 = p.2

/-- **Claim D, forward direction, proved.** Identical methods have identical
objective values, so the performance ratio is one. -/
theorem claim_D_proved (u v : Int) (h : u = v) : ratioIsOne (perfRatio u v) := by
  simp [ratioIsOne, perfRatio, h]

/-- **Claim D, converse direction, proved.** With a nonzero denominator, ratio
one forces the two objective values to agree, so the ratio is a faithful
discriminator between the two methods. -/
theorem claim_D_converse (u v : Int) (hv : v ≠ 0) :
    ratioIsOne (perfRatio u v) → u = v := by
  intro h
  have huv : u * v = v * v := by simpa [ratioIsOne, perfRatio] using h
  have hpos : 0 < v ∨ v < 0 := by
    rcases Int.lt_trichotomy v 0 with hlt | hz | hgt
    · exact Or.inr hlt
    · exact absurd hz hv
    · exact Or.inl hgt
  rcases hpos with hgt | hlt
  · rcases Int.lt_trichotomy u v with hu | heq | hu
    · exact absurd huv (Int.ne_of_lt (Int.mul_lt_mul_of_pos_right hu hgt))
    · exact heq
    · exact absurd huv (by have := Int.mul_lt_mul_of_pos_right hu hgt; omega)
  · rcases Int.lt_trichotomy u v with hu | heq | hu
    · exact absurd huv (by have := Int.mul_lt_mul_of_neg_right hu hlt; omega)
    · exact heq
    · exact absurd huv (Int.ne_of_lt (Int.mul_lt_mul_of_neg_right hu hlt))

/-! ## Claim E

Claim E reads `R_k > 1 => exists O in A \ {O_adam}`. As a statement about the
generated algebra it is a tautology or an error: if the ratio differs from one
then the methods differ, so the operator responsible for the difference is
whatever operator produced the different iterate, and nothing forces that
operator to lie in `A`. The document's own framing, "all **observed** speedups
satisfy", is an empirical summary rather than a universally quantified
proposition, and no bounded set of observations establishes a universal claim.
No Lean statement is fabricated for it.
-/

/-! ## Algorithmic instantiation of the surviving content

The one substantive and provable part of the document is the geometric decay
under a contraction operator. Below it is instantiated as an executable
iteration over exact rationals, together with its correctness statement. -/

/-- `k` iterations of the contraction operator `x |-> (num/den) x` applied to
`x0`, returned as the exact pair `(num^k x0, den^k)`. -/
def contractIterate (num den : Int) (k : Nat) (x0 : Int) : Int × Int :=
  (num ^ k * x0, den ^ k)

/-- **Algorithm correctness of the instantiation.** After `k + 1` steps the
exact rational equals `num/den` times the exact rational after `k` steps, stated
as the exact cross-multiplied identity
`numOf(x_{k+1}) * denOf(x_k) * den = num * (numOf(x_k) * denOf(x_{k+1}))`. -/
theorem contractIterate_steps (num den x0 : Int) (k : Nat) :
    numOf (contractIterate num den (Nat.succ k) x0) * denOf (contractIterate num den k x0) * den
      = num * (numOf (contractIterate num den k x0)
          * denOf (contractIterate num den (Nat.succ k) x0)) := by
  simp [contractIterate, numOf, denOf, Int.pow_succ, Int.mul_comm, Int.mul_left_comm,
    Int.mul_assoc]

/-- The exact iterate after `k` steps for `lambda = 1/2`, `x_0 = 1`, used to
instantiate the corrected Claim A numerically at the first three steps. -/
theorem contractIterate_instances :
    contractIterate 1 2 0 1 = (1, 1) ∧ contractIterate 1 2 1 1 = (1, 2) ∧
      contractIterate 1 2 2 1 = (1, 4) := by
  decide

end PCSS.ToProve.OperatorContraction