def speedupScale : Nat := 1000000
def errorScale : Nat := 10000000000000
def toleranceDenom : Nat := 10000
def slackNum : Nat := 10
def minBaseTotal : Nat := 2 * errorScale * toleranceDenom
def balancedSpeedup : Nat := 9601571
def quotientPressureSpeedup : Nat := 19978818
def classFragmentationSpeedup : Nat := 10001282
def numericalCancellationSpeedup : Nat := 9595680
def balancedReconstructionError : Nat := 381469727
def quotientPressureReconstructionError : Nat := 562667847
def classFragmentationReconstructionError : Nat := 1296997070
def numericalCancellationReconstructionError : Nat := 0
def balancedInvariantError : Nat := 165281243
def quotientPressureInvariantError : Nat := 264223537
def classFragmentationInvariantError : Nat := 173214461
def numericalCancellationInvariantError : Nat := 19635164
def relativeReconstructionGate (reNum btNum : Nat) : Prop := reNum * toleranceDenom < btNum + slackNum
def relativeInvariantGate (errNum btNum : Nat) : Prop := errNum * toleranceDenom < btNum + slackNum
def balancedReconstructionRelative : Prop := relativeReconstructionGate balancedReconstructionError minBaseTotal
def quotientPressureReconstructionRelative : Prop := relativeReconstructionGate quotientPressureReconstructionError minBaseTotal
def classFragmentationReconstructionRelative : Prop := relativeReconstructionGate classFragmentationReconstructionError minBaseTotal
def numericalCancellationReconstructionRelative : Prop := relativeReconstructionGate numericalCancellationReconstructionError minBaseTotal
def balancedInvariantRelative : Prop := relativeInvariantGate balancedInvariantError minBaseTotal
def quotientPressureInvariantRelative : Prop := relativeInvariantGate quotientPressureInvariantError minBaseTotal
def classFragmentationInvariantRelative : Prop := relativeInvariantGate classFragmentationInvariantError minBaseTotal
def numericalCancellationInvariantRelative : Prop := relativeInvariantGate numericalCancellationInvariantError minBaseTotal
def speedup_gate : Prop := balancedSpeedup > speedupScale ∧ quotientPressureSpeedup > speedupScale ∧ classFragmentationSpeedup > speedupScale ∧ numericalCancellationSpeedup > speedupScale
def reconstruction_gate : Prop := balancedReconstructionError < errorScale ∧ quotientPressureReconstructionError < errorScale ∧ classFragmentationReconstructionError < errorScale ∧ numericalCancellationReconstructionError < errorScale ∧ balancedReconstructionRelative ∧ quotientPressureReconstructionRelative ∧ classFragmentationReconstructionRelative ∧ numericalCancellationReconstructionRelative
def invariant_gate : Prop := balancedInvariantError < errorScale ∧ quotientPressureInvariantError < errorScale ∧ classFragmentationInvariantError < errorScale ∧ numericalCancellationInvariantError < errorScale ∧ balancedInvariantRelative ∧ quotientPressureInvariantRelative ∧ classFragmentationInvariantRelative ∧ numericalCancellationInvariantRelative
theorem balanced_reconstruction_relative_proven : balancedReconstructionRelative := by decide
theorem quotient_pressure_reconstruction_relative_proven : quotientPressureReconstructionRelative := by decide
theorem class_fragmentation_reconstruction_relative_proven : classFragmentationReconstructionRelative := by decide
theorem numerical_cancellation_reconstruction_relative_proven : numericalCancellationReconstructionRelative := by decide
theorem balanced_invariant_relative_proven : balancedInvariantRelative := by decide
theorem quotient_pressure_invariant_relative_proven : quotientPressureInvariantRelative := by decide
theorem class_fragmentation_invariant_relative_proven : classFragmentationInvariantRelative := by decide
theorem numerical_cancellation_invariant_relative_proven : numericalCancellationInvariantRelative := by decide
theorem speedup_gate_proven : speedup_gate := by decide
theorem reconstruction_gate_proven : reconstruction_gate := by decide
theorem invariant_gate_proven : invariant_gate := by decide
theorem elevated_gate_proven : speedup_gate ∧ reconstruction_gate ∧ invariant_gate := by exact ⟨speedup_gate_proven, reconstruction_gate_proven, invariant_gate_proven⟩
